#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with the following:
# - Configure Nginx so that /redirect_me is redirecting to another page.
# - The redirection must be a “301 Moved Permanently”.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location /redirect_me {
		return 301 https://youtu.be/dQw4w9WgXcQ?si=c5SSrhdJz17xP0kV;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
