#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with the following:
# - Configure Nginx to have a custom HTTP response header.
# - The header name must be X-Served-By and the value must be the hostname of the server.
# - The page must return an HTTP 200 response code.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page." | sudo tee /var/www/html/404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	add_header X-Served-By $HOSTNAME;

	location /redirect_me {
		return 301 https://youtu.be/dQw4w9WgXcQ?si=c5SSrhdJz17xP0kV;
	}

	error_page 404 /404.html;
	location /404 {
		internal;
		root /var/www/html;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
