#!/usr/bin/env bash
# Installs HAProxy version 2.4 with the following configurations:

sudo apt-get update -y
sudo apt-get purge -y haproxy
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" >>/etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "frontend haproxy_frontend
        bind *:80
        mode http
        default_backend haproxy_backend

backend haproxy_backend
        mode http
        balance roundrobin
        server 520666-web-01 54.237.64.41:80 check 
        server 520666-web-02 54.146.84.7:80 check" >>/etc/haproxy/haproxy.cfg

sudo service haproxy reload
