#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine with the following:
# - Install and configure HAproxy on your Ubuntu server.
# - Configure HAproxy so that it send traffic to web-02 and web-03.
# - Make sure that HAproxy can be managed via an init script.

apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >>/etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "frontend haproxy_in
        bind *:80
        default_backend haproxy_out

backend haproxy_out
        balance roundrobin
        server web-02
        server web-03" >>/etc/haproxy/haproxy.cfg
service haproxy restart
