#!/usr/bin/env bash
# Fix the nginx server to listen on port 80

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sudo service nginx restart
