#!/usr/bin/env bash
# Fix the nginx server to listen on port 80

sudo apt-get update
sudo apt-get install -y nginx
pid=$(ss -tnlp | grep ':80' | awk '{print $NF}')
if [[ -n "$pid" ]]; then
	kill "$pid"
else
	exit 0
fi
sed -i 's/8080/80/' /etc/nginx/sites-available/default
service nginx start
