#!/usr/bin/env bash
# This script:
#   - Creates a file containing its PID
#   - Displays "To infinity and beyond" indefinitely
#   - Displays "I hate the kill command" when receiving a SIGTERM signal
#   - Displays "Y U no love me?!" when receiving a SIGINT signal
#   - Deletes the file containing its PID and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap "echo 'I hate the kill command' && rm -f /var/run/myscript.pid && exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid" SIGQUIT
echo "$$" >/var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
