#!/usr/bin/env bash
# This shell script prints the content of the file /etc/passwd in a story format
while IFS=: read -r username password userid groupid comment homedir cmdshell; do
	echo "The user $username is part of the group $groupid, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $comment"
done </etc/passwd
