#!/usr/bin/env bash
# This shell script prints 10 times "Best School" but for the 9th iteration,
# prints "Hi" instead
for ((i = 0; i < 10; i++)); do
	if ((i == 8)); then
		echo "Hi"
	else
		echo "Best School"
	fi
done
