#!/usr/bin/env bash
# This shell script prints "Best School" 10 times but if the 9th iteration is reached, it prints "Hi" instead of "Best School"
i=0
while ((i < 10 && ++i)); do
	echo "Best School"
	if ((i == 9)); then
		echo "Hi"
	fi
done
