#!/usr/bin/env bash
# This shell script prints "Best School" 10 times but if the 9th iteration is reached, it prints "Hi" instead of "Best School"
for ((i = 0; i < 10; i++)); do
	if ((i == 8)); then
		echo "Hi"
	else
		echo "Best School"
	fi
done
