#!/usr/bin/env bash
# This shell script prints "Best School" 10 times except on the 4th and 8th iteration where it prints "Bad luck" and "Good luck" respectively
i=0
while ((i < 10 && ++i)); do
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
done
