#!/usr/bin/env bash
# This shell script ptints numbers from 1 to 20... On the 4th, 9th, and 17th iteration, the script prints "bad luck from China", "bad luck from Japan", and "bad luck from Italy" respectively instead of the number
i=0
while ((i < 20 && ++i)); do
	echo $i
	case $i in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
done
