#!/usr/bin/env bash
# This shell script ptints numbers from 1 to 20... On the 4th, 9th, and 17th iteration, the script prints "bad luck from China", "bad luck from Japan", and "bad luck from Italy" respectively instead of the number
i=0
while ((i < 20 && ++i)); do
	echo $i
	if ((i == 4)); then
		echo "bad luck from China"
	elif ((i == 9)); then
		echo "bad luck from Japan"
	elif ((i == 17)); then
		echo "bad luck from Italy"
	fi
done
