#!/usr/bin/env bash
# This shell script gives you information about the school file
if [[ -e school ]]; then
	if [[ -s school ]]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f school ]]; then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
